project:
  type: book

book:
  title: "CMOS VLSI Notebook"
  author: "Ryan Hou"
  date: "02/20/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - circuit.qmd
    - highlevel.qmd
    - cmosbasic.qmd
    - fab.qmd
    - cmoscap.qmd
    - invgates.qmd
    - delay.qmd
    - power.qmd
    - interconnect.qmd
    - robust.qmd
    - sim.qmd
    - combcircuit.qmd
    - seqcircuit.qmd
    - datapath.qmd
    - array.qmd
    - special.qmd
    - methodtools.qmd
    - testdebugverif.qmd
    - summary.qmd
    - interview.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



