project:
  type: book

book:
  title: "Data Structures & Algorithms"
  author: "Ryan Hou"
  date: "2/17/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - foundations.qmd
    - pointers.qmd
    - arrays.qmd
    - strings.qmd
    - streams.qmd
    - abstract.qmd
    - oop.qmd
    - dynamicmem.qmd
    - linkedlist.qmd
    - iterators.qmd
    - recursion.qmd
    - functionobj.qmd
    - error.qmd
    - stacks-queues.qmd
    - complexity.qmd
    - stl.qmd
    - trees.qmd
    - heaps.qmd
    - searching.qmd
    - sorting.qmd
    - hash.qmd
    - graphs.qmd
    - brutegreedy.qmd
    - divideconquer-dp.qmd
    - bbb.qmd
    - summary.qmd
    - tips.qmd
    - problems.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



