project:
  type: book

book:
  title: "Computer Architecture"
  author: "Ryan Hou"
  date: "02/26/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - metrics.qmd
    - inorder.qmd
    - ooo-basics.qmd
    - p6r10k.qmd
    - ooo-memory.qmd
    - branch.qmd
    - cache.qmd
    - prefetch.qmd
    - vmem.qmd
    - multiproc.qmd
    - smt.qmd
    - dlp.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



