project:
  type: book

book:
  title: "Parallel Computer Architecture"
  author: "Ryan Hou"
  date: "mm/dd/year"
  chapters:
    - index.qmd
    - intro.qmd
    - prog.qmd
    - dlp.qmd
    - synch.qmd
    - coherence.qmd
    - consistency.qmd
    - nocs.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



